### ISSUE TITLE
support k8s offline install

### ISSUE THREAD

**Issue by willzhang** [kubesphere/ks-installer#1120]
## reference
https://kubesphere.com.cn/forum/d/2034-kubekey-kubesphere-v3-0-0

## registry support in ClusterConfiguration
```
  registry:
    registryMirrors: []
    insecureRegistries: []
    privateRegistry: dockerhub.kubesphere.local
```
move it to
```
---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.0.0
```
