### ISSUE TITLE
etcd monitor fail

### ISSUE THREAD

**Issue by guoh1988** [kubesphere/ks-installer#1243]
1. ks-3.0 Minimal Installation ,The page is normal
2. create a secret for etcd
```
$ kubectl create ns kubesphere-monitoring-system
$ kubectl -n kubesphere-monitoring-system create secret generic kube-etcd-client-certs  \
--from-file=etcd-client-ca.crt=/etc/kubernetes/pki/etcd/ca.crt  \
--from-file=etcd-client.crt=/etc/kubernetes/pki/etcd/healthcheck-client.crt  \
--from-file=etcd-client.key=/etc/kubernetes/pki/etcd/healthcheck-client.key
```
3.  enable etcd monitoring dashboard installation
```
kubectl edit cc ks-installer -n kubesphere-system
 etcd:
    monitoring: true       # Whether to enable etcd monitoring dashboard installation. You have to create a secret for etcd before you enable it.
    endpointIps: 192.168.208.31,192.168.208.32,192.168.208.33 # etcd cluster EndpointIps, it can be a bunch of IPs here.
    port: 2379              # etcd port
    tlsEnable: true
```
4.Unable to get the etcd node information. Check the Prometheus log and find that the etcd certificate cannot be found. After manually mounting the certificate, the etcd node information can be viewed normally
`/etc/prometheus/secrets/kube-etcd-client-certs/etcd-client-ca.crt`
5.Uninstall KS-3.0 page
./kubesphere-delete.sh
6.In cluster- configuration.yaml Modify configuration，Etcd can be monitored after deployment

```
vim cluster-configuration.yaml
    etcd:
    monitoring: true       # Whether to enable etcd monitoring dashboard installation. You have to create a secret for etcd before you enable it.
    endpointIps: 192.168.208.31,192.168.208.32,192.168.208.33 # etcd cluster EndpointIps, it can be a bunch of IPs here.
    port: 2379              # etcd port
    tlsEnable: true
```
7. status.monitoring is enabled，As a result, the deployment of Prometheus was not updated
roles/ks-monitor/tasks/main.yaml
```
- import_tasks: prometheus.yaml
  when:
    - "status.monitoring is not defined or status.monitoring.status is not defined or status.monitoring.status != 'enabled'"
```

**Comment by KeithTt** [comment]
Same problem here:

![image](https://user-images.githubusercontent.com/15189954/112598514-a7913400-8e49-11eb-8cdd-ce31ba541446.png)

**Comment by penpen-dongE** [comment]
same problem, too.

**Comment by Evsio0n** [comment]
Hi all, for who come to this as the same issue here with crt problem. 
https://kubesphere.io/zh/blogs/kubesphere-etcd/ 


The solution for me is that need manually add a secret for this prometheus to mounting cert.

`kubectl edit prometheuses -n kubesphere-monitoring-system`

```yaml
...
spec:
  secrets:
  - kube-etcd-client-certs
```

Has sovled my issue.
