### ISSUE TITLE
If network is empty, then skip it

### ISSUE THREAD

**Issue by zryfish** [kubesphere/ks-installer#1324]
```
authentication:
  authenticateRateLimiterMaxTries: 10
  authenticateRateLimiterDuration: 10m0s
  loginHistoryRetentionPeriod: 168h
  maximumClockSkew: 10s
  multipleLogin: False
  kubectlImage: kubesphere/kubectl:v1.17.0
  jwtSecret: "XutCjdJcEoR0kLRdYD7dXKReAmhhtZp3"
ldap:
  host: openldap.kubesphere-system.svc:389
  managerDN: cn=admin,dc=kubesphere,dc=io
  managerPassword: admin
  userSearchBase: ou=Users,dc=kubesphere,dc=io
  groupSearchBase: ou=Groups,dc=kubesphere,dc=io
redis:
  host: redis.kubesphere-system.svc
  port: 6379
  password: ""
  db: 0
network:
monitoring:
  endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
```
