### ISSUE TITLE
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition

### ISSUE THREAD

**Issue by gnuhub** [kubesphere/ks-installer#1355]

**Comment by JohnNiang** [comment]
But if I upgraded the version, something went wrong...

```bash
❯ kubectl apply -f kubesphere-installer.yaml 
namespace/kubesphere-system created
serviceaccount/ks-installer created
clusterrole.rbac.authorization.k8s.io/ks-installer created
clusterrolebinding.rbac.authorization.k8s.io/ks-installer created
deployment.apps/ks-installer created
The CustomResourceDefinition "clusterconfigurations.installer.kubesphere.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
```

**Comment by kalavt** [comment]
got same error on k8s v1.22.0 & kubeSphere v3.1.1
`kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.1.1/kubesphere-installer.yaml`

**Comment by kalavt** [comment]
update: resolved by
1. change apiVersion: apiextensions.k8s.io/v1beta1 to apiVersion: apiextensions.k8s.io/v1
2.  add schema definenation
  ```
spec:
  group: installer.kubesphere.io
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
```
