### ISSUE TITLE
kubeedge's cloudcore component advertiseAddress configuration format is wrong

### ISSUE THREAD

**Issue by wenhuwang** [kubesphere/ks-installer#1532]
Ks-installer Version: v3.1.0
cluster-configuration.yaml:
```
···
    kubeedge:
    enabled: true
    cloudCore:
      nodeSelector: {"node-role.kubernetes.io/worker": ""}
      tolerations: []
      cloudhubPort: "10000"
      cloudhubQuicPort: "10001"
      cloudhubHttpsPort: "10002"
      cloudstreamPort: "10003"
      tunnelPort: "10004"
      cloudHub:
        advertiseAddress: # At least a public IP Address or an IP which can be accessed by edge nodes must be provided
          - 10.10.52.70            # Causion!: Leave this entry to empty will cause CloudCore to exit abnormally once KubeEdge is enabled.
          - 10.10.52.71
          - 10.10.52.72
        nodeLimit: "100"
```
![image](https://user-images.githubusercontent.com/16423072/121312412-ec504580-c937-11eb-9846-407c81692ab9.png)
![image](https://user-images.githubusercontent.com/16423072/121312571-16096c80-c938-11eb-97ae-8be3bfb2a8d2.png)

/kind bug
/assign @wenhuwang
