### ISSUE TITLE
monitoring stack will be installed when using the external prometheus stack

### ISSUE THREAD

**Issue by lshmouse** [kubesphere/ks-installer#1617]
After https://github.com/kubesphere/ks-installer/pull/1528,  we install kubesphere with an external prometheus stack, but we found the  prometheus stack of kubesphere also will be installed in namespace kubesphere-monitoring-system, which may conflict with existing prometheus stack like: node exporter.

```
     monitoring:                                                                                      
       type: external   # Whether to specify the external prometheus stack, and need to modify the endpoint at the next line.
       endpoint: http://prometheus.kube-system.svc:9090 # Prometheus endpoint to get metrics data     
       grafana: true                                                                                  
       type: "kubesphere"    
```

we need a config to disable the prometheus stack in monitoring role.
