### ISSUE TITLE
fluentbit-operator resources.limits.memory fixed to 50Mi, which leads to oom

### ISSUE THREAD

**Issue by smallersoup** [kubesphere/ks-installer#1949]
fluentbit-operator resources.limits.memory is not configurable, but fixed to 50Mi, which leads to oom, and can only temporarily modify deployment yaml manually

**Comment by smallersoup** [comment]
github.com/kubesphere/ks-installer/roles/common/templates/custom-fluentbit-operator-deployment.yaml.j2
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fluentbit-operator
  namespace: kubesphere-logging-system
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: fluentbit-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/name: fluentbit-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
        app.kubernetes.io/name: fluentbit-operator
    spec:
      volumes:
      - name: env
        emptyDir: {}
{% if common.containersLogMountedPath is defined and common.containersLogMountedPath != "" %}
{% else %}
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
{% endif %}
      initContainers:
      - name: setenv
        image: {{ docker_repo }}:{{ docker_tag }}
        command:
        - /bin/sh
        - '-c'
        - set -ex;
{% if common.containersLogMountedPath is defined and common.containersLogMountedPath != "" %}
          echo DOCKER_ROOT_DIR={{ common.containersLogMountedPath }} > /fluentbit-operator/fluent-bit.env
{% else %}
          echo DOCKER_ROOT_DIR=$(docker info -f {{'{{.DockerRootDir}}'}}) > /fluentbit-operator/fluent-bit.env
{% endif %}
        volumeMounts:
        - name: env
          mountPath: /fluentbit-operator
{% if common.containersLogMountedPath is defined and common.containersLogMountedPath != "" %}
{% else %}
        - name: dockersock
          readOnly: true
          mountPath: /var/run/docker.sock
{% endif %}
      containers:
      - name: fluentbit-operator
        image: {{ fluentbit_operator_repo }}:{{ fluentbit_operator_tag }}
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 20Mi
        volumeMounts:
        - name: env
          mountPath: /fluentbit-operator
      serviceAccountName: fluentbit-operator
```
