### ISSUE TITLE
An error is reported in the ks-installer log: ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by smallersoup** [kubesphere/ks-installer#1950]
kubesphere version：v3.1.1

When I refer to the [Service Topology official documentation](https://kubesphere.io/zh/docs/pluggable-components/service-topology/) and modify the network.topology.type in the cluster configuration to weave-scope, I go to one of my project, navigate to Services under Application Workloads, and I can not see a topology of my Services on the Service Topology tab page. But I see all weave Pod is Running：
```shell
# kubectl get pod -n weave 
NAME                                         READY   STATUS    RESTARTS   AGE
weave-scope-agent-24j5j                      1/1     Running   0          22h
weave-scope-agent-2tv7t                      1/1     Running   0          22h
weave-scope-agent-2zbd9                      1/1     Running   0          22h
weave-scope-agent-8gr4k                      1/1     Running   0          22h
weave-scope-agent-ffzc7                      1/1     Running   0          22h
weave-scope-agent-fxn8f                      1/1     Running   0          22h
weave-scope-agent-kt4p7                      1/1     Running   0          22h
weave-scope-agent-mhxh5                      1/1     Running   0          22h
weave-scope-agent-xh24c                      1/1     Running   0          22h
weave-scope-app-65bc654575-vl99x             1/1     Running   0          22h
weave-scope-cluster-agent-6b4d656cd6-rb46t   1/1     Running   0          22h
```

```shell
PLAY RECAP *********************************************************************
localhost                  : ok=33   changed=20   unreachable=0    failed=0    skipped=13   rescued=0    ignored=0   

Start installing monitoring
Start installing multicluster
Start installing openpitrix
Start installing network
Start installing auditing
Start installing devops
Start installing logging
**************************************************
Waiting for all tasks to be completed ...
task multicluster status is successful  (1/7)
task openpitrix status is successful  (2/7)
task monitoring status is failed  (3/7)
task network status is successful  (4/7)
task auditing status is successful  (5/7)
task logging status is successful  (6/7)
task devops status is successful  (7/7)
**************************************************
Collecting installation results ...
Traceback (most recent call last):
  File "/hooks/kubesphere/installRunner.py", line 573, in <module>
    main()
  File "/hooks/kubesphere/installRunner.py", line 568, in main
    resultState = getResultInfo()
  File "/hooks/kubesphere/installRunner.py", line 234, in getResultInfo
    jobList.sort(
  File "/hooks/kubesphere/installRunner.py", line 235, in <lambda>
    key=lambda x: int(x.split('-')[0])
ValueError: invalid literal for int() with base 10: 'd893331e'
2022-04-19T15:01:03+08:00 ERROR    : TASK_RUN TASK_HOOK_RUN 'kubesphere/installRunner.py' on 'KUBE_EVENTS' failed. Will retry after delay. Failed count is 1. Error: kubesphere/installRunner.py FAILED: exit status 1
2022-04-19T15:01:03+08:00 INFO     : TASK_RUN Delay for 5s
```

**Comment by smallersoup** [comment]
kubesphere version：v3.1.1
clusterconfiguration ks-installer：
```yaml
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  creationTimestamp: "2022-04-19T07:01:08Z"
  labels:
    version: v3.1.1
  name: ks-installer
  namespace: kubesphere-system
spec:
  alerting:
    enabled: false
  auditing:
    enabled: true
  authentication:
    jwtSecret: Zfxtpvyj5Wo8TvslGT7lApFVJ1hCNhij
  common:
    es:
      basicAuth:
        enabled: true
        password: OYT9q9A597zR39b3eXO3sXH8
        username: elastic
      elasticsearchDataVolumeSize: 20Gi
      elasticsearchMasterVolumeSize: 4Gi
      elkPrefix: logstash
      externalElasticsearchPort: "9200"
      externalElasticsearchUrl: es-for-ks-es-http.elastic-system.svc.t2.test.xdf.cn
      logMaxAge: 4
    minioVolumeSize: 20Gi
    monitoring:
      endpoint: http://prometheus-k8s.monitoring.svc:9090
      type: external
    openldap:
      enabled: true
    openldapVolumeSize: 2Gi
    redis:
      enabled: true
    redisVolumSize: 2Gi
  console:
    enableMultiLogin: true
    port: 30880
  devops:
    enabled: true
    jenkinsJavaOpts_MaxRAM: 4g
    jenkinsJavaOpts_Xms: 2048m
    jenkinsJavaOpts_Xmx: 2048m
    jenkinsMemoryLim: 8Gi
    jenkinsMemoryReq: 4096Mi
    jenkinsVolumeSize: 8Gi
  etcd:
    endpointIps: localhost
    monitoring: false
    port: 2379
    tlsEnable: true
  events:
    enabled: false
    ruler:
      enabled: true
      replicas: 2
  kubeedge:
    cloudCore:
      cloudHub:
        advertiseAddress:
        - ""
        nodeLimit: "100"
      cloudhubHttpsPort: "10002"
      cloudhubPort: "10000"
      cloudhubQuicPort: "10001"
      cloudstreamPort: "10003"
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      service:
        cloudhubHttpsNodePort: "30002"
        cloudhubNodePort: "30000"
        cloudhubQuicNodePort: "30001"
        cloudstreamNodePort: "30003"
        tunnelNodePort: "30004"
      tolerations: []
      tunnelPort: "10004"
    edgeWatcher:
      edgeWatcherAgent:
        nodeSelector:
          node-role.kubernetes.io/worker: ""
        tolerations: []
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      tolerations: []
    enabled: false
  local_registry: ""
  logging:
    enabled: true
    logsidecar:
      enabled: true
      replicas: 2
  metrics_server:
    enabled: false
  monitoring:
    prometheusMemoryRequest: 400Mi
    prometheusVolumeSize: 20Gi
    storageClass: ""
  multicluster:
    clusterRole: member
  network:
    ippool:
      type: none
    networkpolicy:
      enabled: false
    topology:
      type: weave-scope
  openpitrix:
    enabled: false
    store:
      enabled: false
  persistence:
    storageClass: ""
  servicemesh:
    enabled: false
status:
  core:
    enabledTime: 2022-04-19T15:04:08CST
    status: enabled
  fluentbit:
    enabledTime: 2022-04-19T15:03:38CST
    status: enabled
  minio:
    enabledTime: 2022-04-19T15:03:20CST
    status: enabled
  network:
    topology:
      enabledTime: 2022-04-19T15:04:40CST
      status: enabled
  openldap:
    enabledTime: 2022-04-19T15:03:12CST
    status: enabled
  redis:
    enabledTime: 2022-04-19T15:03:06CST
    status: enabled
```

kubesphere 相关的pod：
```shell
# kubectl get pod -A | grep kubesphere
kubesphere-controls-system      default-http-backend-857d7b6856-vjxgz                        1/1     Running            0          47d
kubesphere-controls-system      kubectl-admin-58f985d8f6-w6pbh                               1/1     Running            0          20h
kubesphere-devops-system        ks-jenkins-559cfc8-sm5d9                                     1/1     Running            1          54d
kubesphere-devops-system        s2ioperator-0                                                1/1     Running            0          3m42s
kubesphere-logging-system       fluent-bit-2vjtb                                             1/1     Running            1          59d
kubesphere-logging-system       fluent-bit-75sx4                                             1/1     Running            0          59d
kubesphere-logging-system       fluent-bit-8chnf                                             1/1     Running            2          54d
kubesphere-logging-system       fluent-bit-9fm6j                                             1/1     Running            2          59d
kubesphere-logging-system       fluent-bit-br9qb                                             1/1     Running            1          59d
kubesphere-logging-system       fluent-bit-cb4rk                                             1/1     Running            2          55d
kubesphere-logging-system       fluent-bit-dq2m4                                             1/1     Running            0          57d
kubesphere-logging-system       fluent-bit-nvrwg                                             1/1     Running            1          59d
kubesphere-logging-system       fluent-bit-qpp6f                                             1/1     Running            1          54d
kubesphere-logging-system       fluentbit-operator-85cbc8c7b6-64d22                          1/1     Running            0          9m32s
kubesphere-logging-system       kube-auditing-operator-697658f8d-7b4bk                       1/1     Running            0          47d
kubesphere-logging-system       kube-auditing-webhook-deploy-9484b5ff-2jvng                  1/1     Running            0          54d
kubesphere-logging-system       kube-auditing-webhook-deploy-9484b5ff-l4ggh                  1/1     Running            0          53d
kubesphere-logging-system       logsidecar-injector-deploy-74c66bfd85-9j22s                  2/2     Running            0          54d
kubesphere-logging-system       logsidecar-injector-deploy-74c66bfd85-f2987                  2/2     Running            0          21h
kubesphere-monitoring-system    alertmanager-main-0                                          2/2     Running            0          18h
kubesphere-monitoring-system    alertmanager-main-1                                          2/2     Running            0          55d
kubesphere-monitoring-system    alertmanager-main-2                                          2/2     Running            3          31d
kubesphere-monitoring-system    notification-manager-deployment-674dddcbd9-s684l             1/1     Running            0          54d
kubesphere-monitoring-system    notification-manager-deployment-674dddcbd9-tfqz7             1/1     Running            4          55d
kubesphere-monitoring-system    notification-manager-operator-7877c6574f-9fr56               2/2     Running            5          54d
kubesphere-system               ks-apiserver-f9f47568c-8rwss                                 1/1     Running            0          15h
kubesphere-system               ks-apiserver-f9f47568c-9pdp8                                 1/1     Running            0          15h
kubesphere-system               ks-apiserver-f9f47568c-jbn7g                                 1/1     Running            0          15h
kubesphere-system               ks-console-7494896c94-6ntnr                                  1/1     Running            0          15h
kubesphere-system               ks-console-7494896c94-6xs5f                                  1/1     Running            0          15h
kubesphere-system               ks-console-7494896c94-r99ln                                  1/1     Running            0          15h
kubesphere-system               ks-controller-manager-7684d6b5bd-l48qb                       1/1     Running            0          15h
kubesphere-system               ks-controller-manager-7684d6b5bd-rpzjr                       1/1     Running            0          15h
kubesphere-system               ks-controller-manager-7684d6b5bd-xwn2x                       1/1     Running            0          15h
kubesphere-system               ks-installer-7bd6b699df-g77zx                                1/1     Running            0          21h
kubesphere-system               minio-7bfdb5968b-wrqfh                                       1/1     Running            0          49d
kubesphere-system               mysql-7f64d9f584-g727b                                       1/1     Running            0          54d
kubesphere-system               openldap-0                                                   1/1     Running            0          49d
kubesphere-system               openldap-1                                                   1/1     Running            1          31d
kubesphere-system               openldapadmin-86c8dbb9f5-pfdfq                               1/1     Running            0          20h
kubesphere-system               redis-ha-haproxy-5c6559d588-b2d4s                            1/1     Running            0          54d
kubesphere-system               redis-ha-server-0                                            2/2     Running            0          29d
kubesphere-system               redis-ha-server-1                                            2/2     Running            0          55d
kubesphere-system               redis-ha-server-2                                            2/2     Running            0          53d
```
