### ISSUE TITLE
2.1 plugin installation does not take effect: gitlab and harbor

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/ks-installer#196]
I use command line to install gitlab and harbor：

```bash
kubectl edit cm -n kubesphere-system ks-installer
```

but，it does not work.

/help wanted

**Comment by shaowenchen** [comment]
more info:

```yaml
    harbor:
      enabled: True
      domain:
    gitlab:
      enabled: True
      domain:
```

```bash
[root@master ~]# kubectl get pod -A | grep harbor
[root@master ~]# kubectl get pod -A | grep gitlab
[root@master ~]# kubectl top node
NAME     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
master   1376m        17%    16196Mi         51%
node1    845m         10%    13831Mi         88%
```
