### ISSUE TITLE
cluster-configuration.yaml `#` Comment need on another line

### ISSUE THREAD

**Issue by willzhang** [kubesphere/ks-installer#2035]
cluster-configuration.yaml Format is difficult to read and modify parameters

https://raw.githubusercontent.com/kubesphere/ks-installer/v3.3.0/deploy/cluster-configuration.yaml

the `#` should in top of the yaml values and have a standalone line, otherwise it's hard to read

![kubesphre-cluster-config.png](https://s2.loli.net/2022/06/30/uZ5IAfG9qKwFvDL.png)

before
```
  devops:                  # (CPU: 0.47 Core, Memory: 8.6 G) Provide an out-of-the-box CI/CD system based on Jenkins, and automated workflow tools including Source-to-Image & Binary-to-Image.
    enabled: false             # Enable or disable the KubeSphere DevOps System.
    # resources: {}
    jenkinsMemoryLim: 2Gi      # Jenkins memory limit.
    jenkinsMemoryReq: 1500Mi   # Jenkins memory request.
    jenkinsVolumeSize: 8Gi     # Jenkins volume size.
    jenkinsJavaOpts_Xms: 1200m  # The following three fields are JVM parameters.
    jenkinsJavaOpts_Xmx: 1600m
    jenkinsJavaOpts_MaxRAM: 2g
```
after
```
  # (CPU: 0.47 Core, Memory: 8.6 G) Provide an out-of-the-box CI/CD system based on Jenkins, and automated workflow tools including Source-to-Image & Binary-to-Image.
  devops: 
    # Enable or disable the KubeSphere DevOps System.  
    enabled: false             
    # resources: {}
	# Jenkins memory limit.
    jenkinsMemoryLim: 2Gi   
    # Jenkins memory request.	
    jenkinsMemoryReq: 1500Mi
    # Jenkins volume size.	
    jenkinsVolumeSize: 8Gi    
    # The following three fields are JVM parameters.	
    jenkinsJavaOpts_Xms: 1200m  
    jenkinsJavaOpts_Xmx: 1600m
    jenkinsJavaOpts_MaxRAM: 2g
```
