### ISSUE TITLE
builder-base image with wrong tag v3.2.0-podman

### ISSUE THREAD

**Issue by willzhang** [kubesphere/ks-installer#2110]
kubekey v2.2.2 kubesphere v3.3.0

```
root@ubuntu:/data/kubekey# cat images-list.txt |grep podman
kubesphere/builder-base:v3.2.2-podman
kubesphere/builder-nodejs:v3.2.0-podman
kubesphere/builder-maven:v3.2.0-podman
kubesphere/builder-maven:v3.2.1-jdk11-podman
kubesphere/builder-python:v3.2.0-podman
kubesphere/builder-go:v3.2.0-podman
kubesphere/builder-go:v3.2.2-1.16-podman
kubesphere/builder-go:v3.2.2-1.17-podman
kubesphere/builder-go:v3.2.2-1.18-podman
```

but in jenkins-casc-config it's builder-base:v3.2.0-podman

```
jenkins:
  mode: EXCLUSIVE
  numExecutors: 0
  scmCheckoutRetryCount: 2
  disableRememberMe: true

  clouds:
    - kubernetes:
        name: "kubernetes"
        serverUrl: "https://kubernetes.default"
        skipTlsVerify: true
        namespace: "kubesphere-devops-worker"
        credentialsId: "k8s-service-account"
        jenkinsUrl: "http://devops-jenkins.kubesphere-devops-system:80"
        jenkinsTunnel: "devops-jenkins-agent.kubesphere-devops-system:50000"
        containerCapStr: "2"
        connectTimeout: "60"
        readTimeout: "60"
        maxRequestsPerHostStr: "32"
        templates:
          - name: "base"
            namespace: "kubesphere-devops-worker"
            label: "base"
            nodeUsageMode: "NORMAL"
            idleMinutes: 0
            containers:
            - name: "base"
              image: "dockerhub.kubekey.local/kubesphere/builder-base:v3.2.0-podman"
```
