### ISSUE TITLE
k8s 1.26.7 / ks-installer v3.4.0 opensearch install error

### ISSUE THREAD

**Issue by soulmz** [kubesphere/ks-installer#2241]
```bash

TASK [common : ks-logging | Debug opensearch_host] *****************************
ok: [localhost] => {
    "msg": {
        "changed": true,
        "cmd": "/usr/local/bin/kubectl get cm -n kubesphere-system kubesphere-config -o jsonpath='{.data.kubesphere\\.yaml}' | grep \"logging:\" -A 2 | grep 
\"host\" | awk '{print $2}'\n",
        "delta": "0:00:00.158365",
        "end": "2023-10-17 16:48:08.611449",
        "failed": false,
        "failed_when_result": false,
        "rc": 0,
        "start": "2023-10-17 16:48:08.453084",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "https://opensearch-cluster-data.kubesphere-logging-system.svc:9200",
        "stdout_lines": [
            "https://opensearch-cluster-data.kubesphere-logging-system.svc:9200"
        ]
    }
}

TASK [common : KubeSphere | Deploying opensearch-logging] **********************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install opensearch-master /kubesphere/kubesphere/opensearch/opensearch
-2.6.0.tgz -f /kubesphere/kubesphere/opensearch/custom-values-opensearch-master.yaml --namespace kubesphere-logging-system && /usr/local/bin/helm upgrade --i
nstall opensearch-data  /kubesphere/kubesphere/opensearch/opensearch-2.6.0.tgz  -f /kubesphere/kubesphere/opensearch/custom-values-opensearch-data.yaml --nam
espace kubesphere-logging-system\n", "delta": "0:00:00.106976", "end": "2023-10-17 16:48:09.446723", "msg": "non-zero return code", "rc": 1, "start": "2023-1
0-17 16:48:09.339747", "stderr": "Error: failed to parse /kubesphere/kubesphere/opensearch/custom-values-opensearch-master.yaml: error converting YAML to JSO
N: yaml: line 276: mapping values are not allowed in this context", "stderr_lines": ["Error: failed to parse /kubesphere/kubesphere/opensearch/custom-values-
opensearch-master.yaml: error converting YAML to JSON: yaml: line 276: mapping values are not allowed in this context"], "stdout": "Release \"opensearch-mast
er\" does not exist. Installing it now.", "stdout_lines": ["Release \"opensearch-master\" does not exist. Installing it now."]}

PLAY RECAP *********************************************************************
localhost                  : ok=48   changed=41   unreachable=0    failed=1    skipped=82   rescued=0    ignored=0   

```

cluster-config 配置如下：
```yaml
    opensearch:
      basicAuth:
        enabled: true
        password: admin
        username: admin
      dashboard:
        enabled: false
      data:
        replicas: 3
        volumeSize: 80Gi
      enabled: true
#      externalOpensearchHost: ""
#      externalOpensearchPort: ""
      logMaxAge: 14
      master:
        replicas: 3
        volumeSize: 20Gi
      nodeSelector:
        node-role.kubernetes.io/k8s-component: ""
      opensearchPrefix: whizard
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/k8s-component
        operator: Exists

```

去掉容忍 tolerations 配置 ，是没问题的。目测是 tolerations 生成 yaml 的格式转换有问题。
