### ISSUE TITLE
Failed to install logging and service mesh component after uninstalling 

### ISSUE THREAD

**Issue by gzymomo** [kubesphere/ks-installer#2278]
## Version
   kubesphere: 3.4.1
   k8s: v1.23.14

## Uninstalling doc： 

https://www.kubesphere.io/docs/v3.4/pluggable-components/uninstall-pluggable-components/

## Clusterconfiguration 

``` yaml
  ...
  common:
    es:
      basicAuth:
        enabled: false
        password: ''
        username: ''
      data:
        volumeSize: 20Gi
      elkPrefix: logstash
      enabled: true
      externalElasticsearchHost: ''
      externalElasticsearchPort: ''
      externalElasticsearchUrl: ''
      logMaxAge: 7
      master:
        volumeSize: 4Gi
    ...
    opensearch:
      basicAuth:
        enabled: false
        password: ''
        username: ''
      data:
        volumeSize: 20Gi
      enabled: true
      logMaxAge: '7'
      master:
        volumeSize: 4Gi
      opensearchPrefix: whizard
  logging:
    containerruntime: docker
    enabled: true
    logsidecar:
      enabled: true
      replicas: 2
  servicemesh:
    enabled: true
    istio:
      components:
        cni:
          enabled: false
        ingressGateways:
          - enabled: false
            name: istio-ingressgateway
   ...

```

## After instanlling：

![image](https://github.com/kubesphere/ks-installer/assets/22019924/71f0b765-cfc4-4c29-9683-9b909f998f5a)

![image](https://github.com/kubesphere/ks-installer/assets/22019924/29051afa-6801-4e62-bcfe-c021ac4a7923)
