### ISSUE TITLE
support local registry when installing nvidia-dcgm-exporter

### ISSUE THREAD

**Issue by cheriL** [kubesphere/ks-installer#2292]
The `local_registry` does not take effect when installing dcgm-exporter. 

ClusterConfiguration:
```
spec:
  local_registry: registry.local
  monitoring:
    gpu:
      nvidia_dcgm_exporter:
        enabled: true 
```
`k -n kubesphere-monitoring-system get ds nvidia-dcgm-exporter -o jsonpath="{.spec.template.spec.containers[0].image}"`:
```
nvcr.io/nvidia/k8s/dcgm-exporter:2.1.8-2.4.0-rc.3-ubuntu18.04%
```
