### ISSUE TITLE
kubekey --with-kubesphere 镜像路径找不到

### ISSUE THREAD

**Issue by huyouba1** [kubesphere/ks-installer#2306]
```
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.4.1
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  local_registry: "dockerhub.kubekey.local"   #已经设置为私有仓库，并且离线镜像包含
  # dev_tag: ""
  etcd:
    monitoring: false
    endpointIps: localhost
    port: 2379
    tlsEnable: true
```

离线镜像列表
```
  - registry.cn-beijing.aliyuncs.com/kubesphereio/k8s-dns-node-cache:1.15.12
  - registry.cn-beijing.aliyuncs.com/kubesphereio/ks-installer:v3.4.1
  - registry.cn-beijing.aliyuncs.com/kubesphereio/ks-apiserver:v3.4.1
  - registry.cn-beijing.aliyuncs.com/kubesphereio/ks-console:v3.4.1
  - registry.cn-beijing.aliyuncs.com/kubesphereio/ks-controller-manager:v3.4.1
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kubectl:v1.22.0
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kubectl:v1.21.0
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kubectl:v1.20.0
  - registry.cn-beijing.aliyuncs.com/kubesphereio/kubefed:v0.8.1
  - registry.cn-beijing.aliyuncs.com/kubesphereio/tower:v0.2.1
  - registry.cn-beijing.aliyuncs.com/kubesphereio/redis:6.2.6-alpine
```

但是在真实部署的时候，镜像拉取位置不对应，看着像是 ks-installer 自己维护了镜像仓库配置。

```
kube-system         snapshot-controller-0                          0/1     ImagePullBackOff        0             33m
kubesphere-system   ks-core-post-delete-crd-dxnhk                  0/1     ImagePullBackOff        0             44m
kubesphere-system   ks-core-post-patch-system-ns-9mr5q             0/1     ImagePullBackOff        0             46m
kubesphere-system   ks-installer-5d7849b4d8-r6d6l                  1/1     Running                 0             34m
kubesphere-system   redis-64d79d4fb-8vk9c                          0/1     Init:ImagePullBackOff   0             33m


# describe po  redis-64d79d4fb-8vk9c

  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  33m                    default-scheduler  Successfully assigned kubesphere-system/redis-64d79d4fb-8vk9c to master3
  Normal   Pulling    32m (x4 over 33m)      kubelet            Pulling image "dockerhub.kubekey.local/library/redis:5.0.14-alpine"
  Warning  Failed     32m (x4 over 33m)      kubelet            Failed to pull image "dockerhub.kubekey.local/library/redis:5.0.14-alpine": rpc error: code = Unknown desc = Error response from daemon: unknown: repository library/redis not found
  Warning  Failed     32m (x4 over 33m)      kubelet            Error: ErrImagePull
  Warning  Failed     32m (x6 over 33m)      kubelet            Error: ImagePullBackOff
  Normal   BackOff    3m43s (x131 over 33m)  kubelet            Back-off pulling image "dockerhub.kubekey.local/library/redis:5.0.14-alpine"
```

**Comment by huyouba1** [comment]
> try to set: <img alt="Image" width="1013" src="https://private-user-images.githubusercontent.com/54946465/448210639-9fd873a6-3480-4bd9-b2df-6b2ec677b5cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDg0MDgxMzgsIm5iZiI6MTc0ODQwNzgzOCwicGF0aCI6Ii81NDk0NjQ2NS80NDgyMTA2MzktOWZkODczYTYtMzQ4MC00YmQ5LWIyZGYtNmIyZWM2NzdiNWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNTI4VDA0NTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNWUyNzUwNWJhZTBkMmVkNjIyN2I4MjNhNTdiNTExZjA2ZDczYWQ2NTVkNjU5ZmQ3YWNiMjdlMzg0MzY5ZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lM7Z7TXba5nyk21KrB1PGRyFOzISm57cxGjsk7B2v8Y">

不太合适，该配置为kubekey cluster 配置。和ks-installer没有直接的关联关系

**Comment by redscholar** [comment]
[https://github.com/kubesphere/ks-installer/blob/cdd3d677f2bbdcd8c97186bf569cbc9c1deda82d/roles/download/defaults/main.yml#L15-L20
配置](https://github.com/kubesphere/ks-installer/blob/v3.4.1/roles/download/defaults/main.yml)
这里是所有镜像的配置。可以在clusterconfiguration资源里面进行修改。

**Comment by huyouba1** [comment]
> [https://github.com/kubesphere/ks-installer/blob/cdd3d677f2bbdcd8c97186bf569cbc9c1deda82d/roles/download/defaults/main.yml#L15-L20 配置](https://github.com/kubesphere/ks-installer/blob/v3.4.1/roles/download/defaults/main.yml) 这里是所有镜像的配置。可以在clusterconfiguration资源里面进行修改。

非常感谢，就是缺这样一个配置，后续继续学习一下。
```
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.4.1
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  local_registry: dockerhub.kubekey.local
  namespace_override: kubesphereio   # 添加此段
  # dev_tag: ""
```
