### ISSUE TITLE
不支持helm3

### ISSUE THREAD

**Issue by errorcode7** [kubesphere/ks-installer#480]
默认使用helm3，安装报错如下：
TASK [preinstall : check helm status] ******************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm list\n", "delta": "0:00:00.698740", "end": "2019-11-14 02:46:29.347261", "msg": "non-zero return code", "rc": 1, "start": "2019-11-14 02:46:28.648521", "stderr": "Error: could not find tiller", "stderr_lines": ["Error: could not find tiller"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [preinstall : Stop if Helm is not available] ******************************
fatal: [localhost]: FAILED! => {
    "assertion": "helm_check.rc == 0", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "Helm is not available"
}

**Comment by Forest-L** [comment]
通过描述，应该是通过ks-only方式部署的，
1、首先你要确保helm3安装正确；
2、helm3去掉了tiller服务端，但在机器上helm list是正确指令

**Comment by daiqingliang** [comment]
# 用helm 2.14.3版本

## 安装helm
1.https://github.com/helm/helm/releases 下载2.14.3版本
helm-v2.14.3-linux-amd64.tar

2.复制到服务器

3.开始helm
```tar -zxvf helm-v2.14.3-linux-amd64.tar.gz```
```sudo mv linux-amd64/helm /usr/local/bin/helm```
#验证安装成功
```helm help```

## 安装tiller

vim tiller.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
```

#执行安装
```kubectl create -y tiller.yaml```
#用阿里云tiller镜像及tiller账户初始化helm, 将tiller部署到[k8s] deployment下.
```helm init --service-account tiller --upgrade --tiller-image=registry.cn-hangzhou.aliyuncs.com/google_containers/tiller:v2.14.3```
## 验证完成安装
```helm version```
