### ISSUE TITLE
exiting because of error: log: cannot create log: open /tmp/kube-rbac-proxy.centos01.unknownuser.log.INFO.20191121-073531.18770: permission denied

### ISSUE THREAD

**Issue by huntunshule** [kubesphere/ks-installer#499]
![image](https://user-images.githubusercontent.com/52652738/69316888-b0ca2980-0c74-11ea-88a1-c5ef32db934f.png)

![image](https://user-images.githubusercontent.com/52652738/69316914-be7faf00-0c74-11ea-99b1-4a57a6c6557d.png)
错误如图,尝试了五天都是这一个错误,用的是在k8s系统中创建kubeSphere-minimal.yaml,没有改动文件,请问这个权限的问题是在哪里造成的
18770 main.go:213] Generating self signed cert as no cert is provided

2019-11-21T07:35:31.199545675Z log: exiting because of error: log: cannot create log: open /tmp/kube-rbac-proxy.centos01.unknownuser.log.INFO.20191121-073531.18770: permission denied

这是角色绑定的文件,官方原版,我也是使用的这个

**Comment by huanggze** [comment]
我先看一下 kube-rbac-proxy 的源码 213 行

**Comment by huanggze** [comment]
请问 kubesphere-monitoring-system 下是否有 node-exporter-token Secrets？

**Comment by huanggze** [comment]
```
kubectl get sa -n kubesphere-monitoring-system node-exporter
kubectl get clusterrole node-exporter
kubectl get clusterrolebinding node-exporter
```

**Comment by huntunshule** [comment]
> ```
> kubectl get sa -n kubesphere-monitoring-system node-exporter
> kubectl get clusterrole node-exporter
> kubectl get clusterrolebinding node-exporter
> ```

![image](https://user-images.githubusercontent.com/52652738/69322012-102d3700-0c7f-11ea-9e38-e18dcaa4377d.png)

**Comment by huntunshule** [comment]
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kube-ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: kube-ops
```
这是之前的那个

**Comment by huntunshule** [comment]
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kube-ops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: kube-ops
```
这是之前的那个

**Comment by huntunshule** [comment]
再kube-rbac-proxy的镜像的args里面加入`--logtostderr`,建议所有该镜像都加入该命令
完整的node-export如下:
```
apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  labels:
    app: node-exporter
  name: node-exporter
  namespace: kubesphere-monitoring-system
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - args:
            - --web.listen-address=127.0.0.1:9100
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
            - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
          image: kubesphere/node-exporter:ks-v0.16.0
          name: node-exporter
          resources:
            limits:
              cpu: 250m
              memory: 180Mi
            requests:
              cpu: 102m
              memory: 180Mi
          volumeMounts:
            - mountPath: /host/proc
              name: proc
              readOnly: false
            - mountPath: /host/sys
              name: sys
              readOnly: false
            - mountPath: /host/root
              mountPropagation: HostToContainer
              name: root
              readOnly: true
        - args:
            - --secure-listen-address=$(IP):9100
            - --upstream=http://127.0.0.1:9100/
            - --logtostderr
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: kubesphere/kube-rbac-proxy:v0.4.1
          name: kube-rbac-proxy
          ports:
            - containerPort: 9100
              hostPort: 9100
              name: https
          resources:
            limits:
              cpu: 20m
              memory: 40Mi
            requests:
              cpu: 10m
              memory: 20Mi
      hostNetwork: true
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: node-exporter
      tolerations:
      - operator: Exists
      volumes:
        - hostPath:
            path: /proc
          name: proc
        - hostPath:
            path: /sys
          name: sys
        - hostPath:
            path: /
          name: root
```
