### ISSUE TITLE
安装日志显示没问题，ks-account服务初始化失败，无法登陆

### ISSUE THREAD

**Issue by zhangpfly** [kubesphere/ks-installer#682]
安装环境：GKE 1.0.4  centos7，4核6G*3

GKE配置：
```
# cat cluster.yml
# If you intened to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
nodes:
- address: 192.168.6.124
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - etcd
  hostname_override: ""
  user: catty
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 192.168.6.125
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  hostname_override: ""
  user: catty
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
- address: 192.168.6.126
  port: "22"
  internal_address: ""
  role:
  - controlplane
  - worker
  hostname_override: ""
  user: catty
  docker_socket: /var/run/docker.sock
  ssh_key: ""
  ssh_key_path: ~/.ssh/id_rsa
  ssh_cert: ""
  ssh_cert_path: ""
  labels: {}
  taints: []
services:
  etcd:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    external_urls: []
    ca_cert: ""
    cert: ""
    key: ""
    path: ""
    uid: 0
    gid: 0
    snapshot: false
    retention: ""
    creation: ""
    backup_config: null
  kube-api:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    service_cluster_ip_range: 10.43.0.0/16
    service_node_port_range: ""
    pod_security_policy: false
    always_pull_images: false
    secrets_encryption_config: null
    audit_log: null
    admission_configuration: null
    event_rate_limit: null
  kube-controller:
    image: ""
    extra_args:
      cluster-signing-cert-file: /etc/kubernetes/ssl/kube-ca.pem
      cluster-signing-key-file: /etc/kubernetes/ssl/kube-ca-key.pem
    extra_binds: []
    extra_env: []
    cluster_cidr: 10.42.0.0/16
    service_cluster_ip_range: 10.43.0.0/16
  scheduler:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
  kubelet:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
    cluster_domain: cluster.local
    infra_container_image: ""
    cluster_dns_server: 10.43.0.10
    fail_swap_on: false
    generate_serving_certificate: false
  kubeproxy:
    image: ""
    extra_args: {}
    extra_binds: []
    extra_env: []
network:
  plugin: canal
  options: {}
  mtu: 0
  node_selector: {}
authentication:
  strategy: x509
  sans: []
  webhook: null
addons: ""
addons_include: []
system_images:
  etcd: rancher/coreos-etcd:v3.4.3-rancher1
  alpine: rancher/rke-tools:v0.1.52
  nginx_proxy: rancher/rke-tools:v0.1.52
  cert_downloader: rancher/rke-tools:v0.1.52
  kubernetes_services_sidecar: rancher/rke-tools:v0.1.52
  kubedns: rancher/k8s-dns-kube-dns:1.15.0
  dnsmasq: rancher/k8s-dns-dnsmasq-nanny:1.15.0
  kubedns_sidecar: rancher/k8s-dns-sidecar:1.15.0
  kubedns_autoscaler: rancher/cluster-proportional-autoscaler:1.7.1
  coredns: rancher/coredns-coredns:1.6.5
  coredns_autoscaler: rancher/cluster-proportional-autoscaler:1.7.1
  kubernetes: rancher/hyperkube:v1.17.0-rancher1
  flannel: rancher/coreos-flannel:v0.11.0-rancher1
  flannel_cni: rancher/flannel-cni:v0.3.0-rancher5
  calico_node: rancher/calico-node:v3.10.2
  calico_cni: rancher/calico-cni:v3.10.2
  calico_controllers: rancher/calico-kube-controllers:v3.10.2
  calico_ctl: ""
  calico_flexvol: rancher/calico-pod2daemon-flexvol:v3.10.2
  canal_node: rancher/calico-node:v3.10.2
  canal_cni: rancher/calico-cni:v3.10.2
  canal_flannel: rancher/coreos-flannel:v0.11.0
  canal_flexvol: rancher/calico-pod2daemon-flexvol:v3.10.2
  weave_node: weaveworks/weave-kube:2.5.2
  weave_cni: weaveworks/weave-npc:2.5.2
  pod_infra_container: rancher/pause:3.1
  ingress: rancher/nginx-ingress-controller:nginx-0.25.1-rancher1
  ingress_backend: rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1
  metrics_server: rancher/metrics-server:v0.3.6
  windows_pod_infra_container: rancher/kubelet-pause:v0.1.3
ssh_key_path: ~/.ssh/id_rsa
ssh_cert_path: ""
ssh_agent_auth: false
authorization:
  mode: rbac
  options: {}
ignore_docker_version: false
kubernetes_version: ""
private_registries: []
ingress:
  provider: ""
  options: {}
  node_selector: {}
  extra_args: {}
  dns_policy: ""
  extra_envs: []
  extra_volumes: []
  extra_volume_mounts: []
cluster_name: ""
cloud_provider:
  name: ""
prefix_path: ""
addon_job_timeout: 0
bastion_host:
  address: ""
  port: ""
  user: ""
  ssh_key: ""
  ssh_key_path: ""
  ssh_cert: ""
  ssh_cert_path: ""
monitoring:
  provider: ""
  options: {}
  node_selector: {}
restore:
  restore: false
  snapshot_name: ""
dns: null
```

pod状态：
```
# kubectl get pods --all-namespaces
NAMESPACE                      NAME                                            READY   STATUS      RESTARTS   AGE
cattle-system                  cattle-cluster-agent-6c87d7f578-qx449           1/1     Running     0          2d20h
cattle-system                  cattle-node-agent-m7brt                         1/1     Running     0          2d20h
cattle-system                  cattle-node-agent-qjjxc                         1/1     Running     0          2d20h
cattle-system                  cattle-node-agent-tn9j5                         1/1     Running     0          2d20h
ingress-nginx                  default-http-backend-67cf578fc4-2vkzf           1/1     Running     0          2d23h
ingress-nginx                  nginx-ingress-controller-4q6jn                  1/1     Running     0          2d23h
ingress-nginx                  nginx-ingress-controller-q7h2s                  1/1     Running     0          2d23h
kube-system                    canal-6ksbb                                     2/2     Running     0          2d23h
kube-system                    canal-lz8gp                                     2/2     Running     0          2d23h
kube-system                    canal-r7j6l                                     2/2     Running     0          2d23h
kube-system                    coredns-7c5566588d-75v22                        1/1     Running     0          2d23h
kube-system                    coredns-7c5566588d-zvm8g                        1/1     Running     0          2d23h
kube-system                    coredns-autoscaler-65bfc8d47d-zv5qw             1/1     Running     0          2d23h
kube-system                    metrics-server-6b55c64f86-qscqg                 1/1     Running     0          2d23h
kube-system                    rke-coredns-addon-deploy-job-2gmc5              0/1     Completed   0          2d23h
kube-system                    rke-ingress-controller-deploy-job-4qssz         0/1     Completed   0          2d23h
kube-system                    rke-metrics-addon-deploy-job-rrzd5              0/1     Completed   0          2d23h
kube-system                    rke-network-plugin-deploy-job-grx94             0/1     Completed   0          2d23h
kube-system                    tiller-deploy-547d695f46-7zxvk                  1/1     Running     0          2d22h
kubesphere-controls-system     default-http-backend-5d464dd566-9j5k4           1/1     Running     0          3h17m
kubesphere-monitoring-system   kube-state-metrics-566cdbcb48-gwvct             4/4     Running     0          3h16m
kubesphere-monitoring-system   node-exporter-88wmv                             2/2     Running     0          3h16m
kubesphere-monitoring-system   node-exporter-8t2c2                             2/2     Running     0          3h16m
kubesphere-monitoring-system   node-exporter-mvnfz                             2/2     Running     0          3h16m
kubesphere-monitoring-system   prometheus-k8s-0                                3/3     Running     1          3h9m
kubesphere-monitoring-system   prometheus-k8s-system-0                         3/3     Running     1          3h9m
kubesphere-monitoring-system   prometheus-operator-6b97679cfd-7669b            1/1     Running     0          3h16m
kubesphere-system              ks-account-789cd8bbd5-gcrsg                     0/1     Init:1/2    0          151m
kubesphere-system              ks-apigateway-5664c4b76f-jwmqx                  1/1     Running     0          151m
kubesphere-system              ks-apiserver-75f468d48b-bvh8x                   1/1     Running     0          151m
kubesphere-system              ks-console-78bddc5bfb-xs2bt                     1/1     Running     0          151m
kubesphere-system              ks-controller-manager-d4788677-xp4cj            1/1     Running     0          151m
kubesphere-system              ks-installer-75b8d89dff-tdm8v                   1/1     Running     0          153m
kubesphere-system              redis-6fd6c6d6f9-gr4hn                          1/1     Running     0          151m
nfs-client-provisioner-7m559   nfs-client-provisioner-2zsr7-789785b7b5-4xslf   1/1     Running     0          5h28m
nfs-client-provisioner-l2fvk   nfs-client-provisioner-4tgzc-577bcb4d95-qtcrl   1/1     Running     0          2d19h
nfs-client-provisioner         nfs-client-provisioner-845fc6d7cc-pcdjz         1/1     Running     0          3h32m
```

sc pv pvc
```
[root@master2 ~]# kubectl get sc
NAME                   PROVISIONER                                  RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
nfs-client (default)   cluster.local/nfs-client-provisioner         Delete          Immediate           true                   3h33m
nfs164                 cluster.local/nfs-client-provisioner-4tgzc   Delete          Immediate           true                   2d19h
nfs165                 cluster.local/nfs-client-provisioner-2zsr7   Delete          Immediate           true                   5h29m
[root@master2 ~]# 
[root@master2 ~]# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                                           STORAGECLASS   REASON   AGE
pvc-5b88d187-06a1-4b9e-b8fa-813ff4425b1a   20Gi       RWO            Delete           Bound    kubesphere-monitoring-system/prometheus-k8s-system-db-prometheus-k8s-system-0   nfs-client              3h17m
pvc-5d35fb0a-ff56-4233-9a23-c03b41e3da2f   2Gi        RWO            Delete           Bound    kubesphere-system/redis-pvc                                                     nfs-client              152m
pvc-fbc4711e-c23d-45d7-be33-16458f9591be   20Gi       RWO            Delete           Bound    kubesphere-monitoring-system/prometheus-k8s-db-prometheus-k8s-0                 nfs-client              3h17m
[root@master2 ~]# 
[root@master2 ~]# kubectl get pvc --all-namespaces 
NAMESPACE                      NAME                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
kubesphere-monitoring-system   prometheus-k8s-db-prometheus-k8s-0                 Bound    pvc-fbc4711e-c23d-45d7-be33-16458f9591be   20Gi       RWO            nfs-client     3h17m
kubesphere-monitoring-system   prometheus-k8s-system-db-prometheus-k8s-system-0   Bound    pvc-5b88d187-06a1-4b9e-b8fa-813ff4425b1a   20Gi       RWO            nfs-client     3h17m
kubesphere-system              redis-pvc                                          Bound    pvc-5d35fb0a-ff56-4233-9a23-c03b41e3da2f   2Gi        RWO            nfs-client     152m
```

日志状态：
![image](https://user-images.githubusercontent.com/17722518/76728133-d1247380-6790-11ea-838c-c4e437602d12.png)
