### ISSUE TITLE
kubesphere配置

### ISSUE THREAD

**Issue by zryfish** [kubesphere/ks-installer#72]
如下，kubesphere组件配置示例，如果对应组件没有配置，或者对应组件的 host/endpoint/apiserver 为空，则视为禁用

```yaml
mysql:
  host: 10.68.55.55:3306
  username: root
  password: admin
  maxIdleConnections: 10
  maxOpenConnections: 20
  maxConnectionLifeTime: 10s
devops:
  host: http://ks-devops.kubesphere-devops-system.svc
  username: jenkins
  password: kubesphere
  maxConnections: 10
sonarQube:
  host: http://sonarqube.kubesphere-devops-system.svc
  token: ABCDEFG
kubernetes:
  kubeconfig: /Users/zry/.kube/config
  master: https://127.0.0.1:6443
  qps: 1e+06
  burst: 1000000
servicemesh:
  istioPilotHost: http://istio-pilot.istio-system.svc:9090
  jaegerQueryHost: http://jaeger-query.istio-system.svc:80
  servicemeshPrometheusHost: http://prometheus-k8s.kubesphere-monitoring-system.svc
ldap:
  host: http://openldap.kubesphere-system.svc
  managerDN: cn=admin,dc=example,dc=org
  managerPassword: P@88w0rd
  userSearchBase: ou=Users,dc=example,dc=org
  groupSearchBase: ou=Groups,dc=example,dc=org
redis:
  host: 10.10.111.110
  port: 6379
  password: ""
  db: 0
s3:
  endpoint: http://minio.openpitrix-system.svc
  region: us-east-1
  disableSSL: true
  accessKeyID: ABCDEFGHIJKLMN
  secretAccessKey: OPQRSTUVWXYZ
  sessionToken: abcdefghijklmn
  bucket: ssss
openpitrix:
  apiServer: http://api-gateway.openpitrix-system.svc
  token: ABCDEFGHIJKLMN
monitoring:
  endpoint: http://prometheus.kubesphere-monitoring-system.svc
  secondaryEndpoint: http://prometheus.kubesphere-monitoring-system.svc

```
