### ISSUE TITLE
Execute to this point ‘kubectl apply -f kubesphere.yaml ’ to report errors

### ISSUE THREAD

**Issue by Jensen-Lone** [kubesphere/ks-installer#84]
TASK [ks-devops/sonarqube : Sonarqube | Deploy Sonarqube] **********************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-sonarqube  /etc/kubesphere/sonarqube/sonarqube-0.13.5.tgz -f /etc/kubesphere/sonarqube/custom-values-sonarqube.yaml  --namespace kubesphere-devops-system\n", "delta": "0:00:00.424497", "end": "2019-08-24 20:20:58.029648", "msg": "non-zero return code", "rc": 1, "start": "2019-08-24 20:20:57.605151", "stderr": "Error: UPGRADE FAILED: configmaps is forbidden: User \"system:serviceaccount:kube-system:default\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"kube-system\"", "stderr_lines": ["Error: UPGRADE FAILED: configmaps is forbidden: User \"system:serviceaccount:kube-system:default\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"kube-system\""], "stdout": "", "stdout_lines": []}

**Comment by Jensen-Lone** [comment]
[root@k8s-master deploy]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
[root@k8s-master deploy]# helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

**Comment by pixiake** [comment]
https://devopscube.com/install-configure-helm-kubernetes/
Make sure you have a service account with the cluster-admin role defined for Tiller.
```
 helm init --service-account tiller
```

**Comment by leonj1** [comment]
This is what I had to do, hope it helps someone:
```
y# cat cm_rbac.yml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-system-default-list-configmaps
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "kube-system:default" to read configmaps in the "kube-system" namespace.
kind: ClusterRoleBinding
metadata:
  name: read-configmaps
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-system-default-list-configmaps
  apiGroup: rbac.authorization.k8s.io
```
