### ISSUE TITLE
Why there are two notification options? 

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/ks-installer#860]
kubectl edit cc ks-installer -n kubesphere-system

```
···
monitoring:
    alertmanagerReplicas: 1
    notification:
      enabled: true  # 1st
    prometheusMemoryRequest: 400Mi
    prometheusReplicas: 1
    prometheusVolumeSize: 20Gi
  multicluster:
    clusterRole: member
  networkpolicy:
    enabled: true
  notification:
    enabled: true # 2nd
```
