### ISSUE TITLE
在源码中找不到ks-apigateway的service声明文件，也找不到apigateway deployment的声明文件,请问这两个资源是在哪里创建的

### ISSUE THREAD

**Issue by watermelon-brother** [kubesphere/ks-installer#893]
在源码中找不到ks-apigateway的service声明文件，也找不到apigateway deployment的声明文件,请问这两个资源是在哪里创建的

**Comment by watermelon-brother** [comment]
```yaml
apiVersion: v1
data:
  local_config.yaml: |
    server:
      gatewayServer:
        url: http://ks-apigateway.kubesphere-system.svc
        wsUrl: ws://ks-apigateway.kubesphere-system.svc

      http:
        hostname: localhost
        port: 8000
        static:
          production:
            /public: server/public
            /assets: dist/assets
            /dist: dist
      redis:
        port: 6379
        host: redis.kubesphere-system.svc
      redisTimeout: 5000
      sessionTimeout: 7200000
    client:
      version:
        kubesphere: {{ ks_version }}
        kubernetes: {{ kube_version }}
        openpitrix: {{ openpitrix_version }}
      enableKubeConfig: true
kind: ConfigMap
metadata:
  name: ks-console-config
  namespace: kubesphere-system

```
请问上面文件中连接后端的service在安装脚本哪里创建啊
```yaml
gatewayServer:
        url: http://ks-apigateway.kubesphere-system.svc
        wsUrl: ws://ks-apigateway.kubesphere-system.svc
```
安装脚本都找遍了找不到部署ks-apigateway service和ks-apigateway deployment的代码啊!
麻烦知道的说下啊。。。
